# ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼ã®åå‰ã€Actionsä¸Šã«è¡¨ç¤ºã•ã‚Œã‚‹
name: Hello FastlaneğŸ±
# ä½•ã‚’ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã¨ã™ã‚‹ã‹
# ã“ã®å ´åˆè©²å½“ãƒªãƒã‚¸ãƒˆãƒªã«ã©ã®ãƒ–ãƒ©ãƒ³ãƒã§pushã—ã¦ã‚‚ä»¥ä¸‹ã®jobãŒå¿…ãšå®Ÿè¡Œã•ã‚Œã‚‹
on: push

jobs:
  # jobã®keyå
  # è¤‡æ•°ã®jobã‚’ä½œæˆã—ä»–ã®jobã‹ã‚‰ä½¿ç”¨ã™ã‚‹éš›ã«ã¯ã“ã®keyåã‚’ä½¿ç”¨ã™ã‚‹
  # ã‚‚ã—ã“ã®jobã®nameã‚’æŒ‡å®šã—ãªã‹ã£ãŸå ´åˆã¯ã€ã“ã®keyåãŒnameã¨ã—ã¦ä½¿ã‚ã‚Œã‚‹
  build:
    runs-on: macos-latest

    # jobã®åå‰
    name: Run Fastlane Sample
    # å®Ÿè¡Œã™ã‚‹å†…å®¹
    steps:
      - uses: actions/checkout@v3
      - run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
      - run: xcodebuild -version
      - run: bundle install
      - run: bundle exec fastlane hello_fastlane
